# cf. https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Master Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        quarkusMode: [jvm, native]
        include:
          - quarkusMode: native
            dockerImageTag: native
            mvnNativeArg: -Pnative
          - quarkusMode: jvm
            dockerImageTag: latest
            mvnNativeArg: -P!native

    steps:

    # setup
      
    - name: Set up JDK 11
      if: ${{ matrix.quarkusMode == 'jvm' }}
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    - name: Set up GraalVM
      if: ${{ matrix.quarkusMode == 'native' }}
      uses: DeLaGuardo/setup-graalvm@3
    - uses: actions/checkout@v2

    # Maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml ${{ matrix.mvnNativeArg }}
      
    - name: Archive JAR files
      uses: actions/upload-artifact@v2
      with:
        name: jar-${{ matrix.quarkusMode }}
        path: target/*.jar
    - name: Archive Surefire reports
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports-${{ matrix.quarkusMode }}
        path: target/surefire-reports/*.xml

    # Docker

    # cf. https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        dockerfile: src/main/docker/Dokerfile.${{ matrix.quarkusMode }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: fxnn/artixray
        tags: ${{ matrix.dockerImageTag }}
        add_git_labels: true
